name: Prettier Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run Prettier check
        run: git ls-files -z | xargs -0 npx --yes prettier@3 --check --ignore-unknown --
